name: Learning activity types
on: 
  push:
    types: opened
jobs:
  if: false
  log:
    runs-on: ubuntu-server
    steps: 
      - name: Log message
        run: echo "A pull request has been opened"