name: First Workflow
on: 
  workflow_dispatch:
jobs:
  if: false
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hey!!!!!"

      - name: Print goodbye in multiple line
        run: |
          echo "I am going"
          echo "Bubbie"
  
